on:
    push:
        branches:
            - {{cookiecutter.github_default_branch}}
    pull_request:
        branches:
            - {{cookiecutter.github_default_branch}}


name: Linux installation
jobs:
    test-ubuntu:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["{{cookiecutter.python_version}}"]
{% raw %}
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
{% endraw %}
            - name: Install package
              run: pip install .
            - name: Test import
              run: python -c "import {{ cookiecutter.project_slug }}; print('{{ cookiecutter.project_slug }} import successful')"
